import pickle

judges_regexes = ['Judges:|Judges|JUDGES', 'judge|Judge|JUDGE',
' delivered the Opinion of the Court\.| DELIVERED THE OPINION OF THE COURT\.|Delivered the Opinion of the Court\.',
'BEFORE THE ENTIRE', 'Court|court|COURT', ' Sr\.| SR\.', ' Jr\.| JR\.', ' Mr\.| MR\.',
' Sr| SR', ' Jr| JR', ' at the', ' Mr| MR', 'and in the judgment',
'was an appointed', 'S93A0786', 'S93X0787', 'III-A', 'I-V',
'Parts V\(C\), VI, VII and VIII', ' VII', 'Parts V\(C\), VI, VII, and VIII',
'Parts I, II, IV and V\(A\)', 'Part III and V\(B\)', 'Parts V\(C\), VI, VII and VIII',
'Messrs\.', ' stead', 'MOTION FOR EXPEDITED APPEAL IS GRANTED', 'REQUEST FOR ORAL ARGUMENT IS DENIED',
'Section IV\(D\)', 'parts I, II, and III', 'respect|RESPECT|Respect',
'action was submitted', 'Subscribing to the Opinion and Assigning Additional Reasons',
'Pursuant to Ariz\. Const\. art\. VI|pursuant to Ariz\. Const\. art\. VI|Pursuant to Ariz\. Const\. art\. 6|pursuant to Ariz\. Const\. art\. 6',
'Arizona Constitution', 'Pursuant to art\. VI\.|Pursuant to article VI', 'pursuant|Pursuant',
' and Justices', 'None', '\xe2\x80\x94', 'PANEL: ', '\$110W\.', ' but, on administrative leave,',
'Ex parte Reneau L\. Gates \(re\: v\. Palm Harbor Homes\, Inc\.\, et al\.\)',
'All the|all the|ALL THE', 'Circuit|circuit|CIRCUIT', 'except', 'Special Justices',
'Terminix International v\. Jackson', 'Special Justice', 'We Concur|WE CONCUR|We concur',
'Associate Justice', 'Point II', 'Special Chief Justice', 'Chief Justice', 'Justice\.',
'affirmance|Affirmance|AFFIRMANCE', "'s|'S", '\(No\.\s\d*\)', 'AFFIRMED|Affirmed|affirmed',
'AFFIRM|Affirm|affirm', 'grant the petition', 'petition|Petition|PETITION',
'Granted|granted|GRANTED', 'abstaining|Abstaining|ABSTAINING', 'No\.\s\d*',
'Senior', 'Supr\.|Supr', '\xe2\x80\x94', 'Chief Justice', 'Chief Judge', ' but ',
'Justices|JUSTICES|justices', 'JUSTICE\.', 'JUSTICE|Justice|justice',
'announced|Announced|ANNOUNCED', '\*Link to the text of the note', 'Ariz\.Const\.',
'art\. VI', ' art\.', 'Link to the text of the note', 'to the', 'prior',
'oral argument|argument', 'resigned', 'chief|Chief|CHIEF', 'AUTHOR', 'nonrecusal|NONRECUSAL|Nonrecusal',
'deeming', 'temporary', 'filed:', 'filed a|file a', 'President', 'Intermediate|intermediate|INTERMEDIATE',
'Associate|ASSOCIATE|associate', 'reasons|REASONS|Reasons|reason|REASON|Reason',
'Superior', 'constituting the', 'En Banc|en Banc', 'In Banc', 'cases|Cases|CASES',
'agreement|Agreement|AGREEMENT', '"', ' all | All | ALL ', 'Present|PRESENT|present',
'APPEALS', ' THE', '\xc3\x81', 'WITHOUT', 'WITH', 'ASSIGNED BY REASON OF VACANCY|VACANCY|Vacancy',
'THIS', 'PELICONES|Pelicones', 'member|Member|MEMBER', 'disposition|Disposition|DISPOSITION',
' right| Right| RIGHT', 'DISSENTS', 'WRITTEN|written|Written', 'WITHOUT|without',
' took| TOOK| Took', 'Rule IV', ' IV', 'C\. J\.,', ' J\.,',
'assigned|Assigned|ASSIGNED|ASSIGNS|Assigns|assigns', ' as ', '"Agreement to Arbitrate"',
'Arbitrate\"', 'files a', 'former|Former|FORMER',
'C\.J\.,|Sp\.JJ|Sp\.J\.|Sp\. J\.|C\.J,|J\.P\.T\.|CJ,||A\.J\.V\.C\.J\.,|JJ\.,|Sp\.J\.|Js,|JS,|JJ\.,|JJ,|D\.J\.,|P\.J\.,|P\.\sJ\.,|C\.J\.,|J\.,|J\.| J,|C\. J\.,',
'C\.J\.|C\.J|CJ|JJ\.|Js|JS|JJ\.|JJ|D\.J\.|P\.J\.|P\.\sJ\.|C\.J\.|J\.|J\.|C\. J\.',
'C\.J\.|C\.J|CJ|JJ\.|Js|JS|JJ\.|JJ|D\.J\.|P\.J\.|P\.\sJ\.|C\.J\.|J\.|J\.|C\. J\.',
'Sp\.J\.', 'Part II\.A', 'Part II\.B', 'Parts II', 'Parts I', 'Part II', 'Part I',
'WoWe', 'foregoing|Foregoing|FOREGOING', ' for| For| FOR', '[\(\[].*?[\)\]]',
'III', 'II\(\w\)', 'III\(\w\)', ' II', 'III', 'Associate', 'Vice', '\[\**\d*\]',
'Arbitrate|arbitrate|ARBITRATE', '\xc2', 'BENCH|Bench|bench', '(Before: |BEFORE: )',
'\xa0', '\/', '\(see p', '\(\d\)', '\d', '\(', '\)', '\sI,', ' or ', ' BY',
' FOR', 'I;', 'Voting|VOTING|voting', 'Surrogate', "\'", 'judgment',
'unanimous view of the court', 'unanimous', 'Took no|Took No|took no|TOOK NO',
' No,', 'separately|Separately|SEPARATELY', 'separate|Separate|SEPARATE',
'in place of', 'sections,', 'Sections,', 'sections', 'section,', 'Section,',
'section', 'constituting,', 'en banc,|en banc|En banc|En Banc|EN BANC', '\[',
'\]', 'concurs in the result, without opinion\.', 'all concurring', 'See separate opinion',
'concurring|Concurring|CONCURRING', 'concurrence|Concurrence|CONCURRENCE|Concurrence:',
'concurred', 'concur in', 'Concurs:|CONCURs:', 'concurs|Concurs|CONCURS',
'concur|Concur', 'does', 'consideration', 'Md\.', 'Temporarily', 'Link to, text thee',
'assigns reasons', 'Appeals','retired|RETIRED|Retired|Ret|ret\.', 'assigned|Assigned|ASSIGNED|assignment|Assignment|ASSIGNNMENT',
'The ', ' sat', 'delivered', 'PARTICIPATING', 'participating', 'PARTICIPATING',
'participating', 'Participating', 'did not participate', 'did not sit', 'did not',
'Maricopa County', 'County', 'WRITTEN BY:|Written by:', 'herein', 'not participate',
'participate', 'Presiding|PRESIDING', 'specially|Specially|SPECIALLY', 'special|Special|SPECIAL',
'pro-tem|Pro-Tem|PRO-TEM', 'concurring', 'Concurring', 'concurs in the result, without opinion\.',
'no opinion', 'opinion\.', 'OPINIONS|OPINIONs|opinions|Opinions', 'opinion|Opinion|OPINION',
' full ', 'statement', 'files|file|FILES|FILE', 'Judicial Circuit', 'Part III',
'no part|NO PART|No Part', 'part|Part|PART', 'which|Which|WHICH', 'DENIED|denied',
'Majority|majority|MAJORITY', 'Heard|heard|HEARD', 'joining|JOINING|Joining',
'joined|JOINED|Joined', 'joins|JOINS|Joins', 'join|JOIN|Join', 'takes|taking|Taking|TAKING',
' that', 'as to the rationale', 'the judgment', 'rationale', 'T\.Y\.|T\. Y\.',
'A\.M\.', 'F\.E\.', 'N\.C\.', 'Paul H\.', 'Russell A\.', 'G\. Barry',
' A\.| B\.| C\.| D\.| E\.| F\.| G\.| H\.| I\.| J\.| K\.| L\.| M\.| N\.| O\.| P\.| Q\.| R\.| S\.| T\.| U\.| V\.| W\.| X\.| Y\.| Z\.|',
' A\.| B\.| C\.| D\.| E\.| F\.| G\.| H\.| I\.| J\.| K\.| L\.| M\.| N\.| O\.| P\.| Q\.| R\.| S\.| T\.| U\.| V\.| W\.| X\.| Y\.| Z\.|',
' A\.| B\.| C\.| D\.| E\.| F\.| G\.| H\.| I\.| J\.| K\.| L\.| M\.| N\.| O\.| P\.| Q\.| R\.| S\.| T\.| U\.| V\.| W\.| X\.| Y\.| Z\.|',
' A\.| B\.| C\.| D\.| E\.| F\.| G\.| H\.| I\.| J\.| K\.| L\.| M\.| N\.| O\.| P\.| Q\.| R\.| S\.| T\.| U\.| V\.| W\.| X\.| Y\.| Z\.|',
'BEFORE', 'would', 'this', 'only', 'without', 'with', ' out', 'also', ' of',
' view', ' Not', ' not', ' NOT', ' whom', ' who', 'filed', 'expressing',
'but dissents', 'but dissent', 'but not the dissent', 'dissented','issued',
'foregoing', 'agree','Opposed|opposed|OPPOSED', 'dissents', 'dissenting',
'DISSENTING', 'ENTIRE COURT',' as', 'reversal', 'none', 'Twelfth|Eleventh|Fifth|Tenth|Ninth|Eigth|Seventh|Sixth',
'Mr', 'remand', 'overruling','rehearing', 'OPINION', 'COURT', 'ONLY',
'IN RESULT', ' IN ', 'Dissenting', 'Dissents', 'dissent','Dissent', 'recuses|RECUSES|Recuses',
'recused|RECUSED|Recused', 'recuse|RECUSE|Recuse', 'SEPARATELY','PRO-TEM', 'reserves',
'is disqualified|disqualified|disqualification', 'recused themselves', 'recused|Recused',
'deceased', 'in the result', 'the result', 'result|Result|RESULT', ' acting ',
' and ', ' AND ', ' in a', 'in the', ' In | in ', ' in,',' of', ' OF', ' from',
'herself', 'himself', 'themselves', 'expresses', 'ii', ' cases| Cases', 'case|Case',
' by', 'heard','considered', 'decided','time', 'submission', '\&', 'were designated',
'is designated|designated|designation',' All |ALL ', 'is sitting', 'sitting|SITTING|Sitting',
' sit', ' superior', ' under', 'WHOLE|Whole|whole', 'deny', 'Matter|MATTER|matter',
' otherwise|Otherwise|OTHERWISE', ' leave', ' others| other| Other| OTHER',
' vote|votes to', 'RSA', 'memorandum', 'took no', 'syllabus', 'Appellate District',
'District|district', 'Administrative', 'i-v', 'follows', 'Judicial', 'By:',
'Panel:', ':\s', ':', 'authored|Authored|AUTHORED', ' to ', 'DISSENT', ' each',
'Jr|jr|JR', 'denial', 'Sr|sr|SR','Deceased|deceased|DECEASED','lead|LEAD|Lead',
' was | WAS | Was', ' other', 'writing', 'Writ|writ|WRIT', 'take|TAKE|Take',
'Issued|issued|ISSUED', 'Madame|MADAME|madame', 'Visiting|VISITING|visiting',
'acting|ACTING|Acting', 'having|Having|HAVING', 'reverse',' is ', 'Third',
' John ', ' to ', ', to ', ' ir ', 'Modification', 'Vacation', ',d,',
'Division Two|Two', 'dS', 'NOTE', 'dI', 'dX', 'were', 'pursuant', 'determination ',
'Division One', 'article IV', 'Article|ARTICLE|article', 'Arizona', 'Second',
'Council', 'Chairperson', 'not on panel|on panel|panel', 'Division Four',
'to conviction|conviction', 'to sentence|sentence', 'additional', 'following',
'subscribes|subscribe', 'ORAL ARGUMENT','DENIAL', ' ONE ', 'TWO', 'THREE',
' have', 'unconstitutional', 'follow', 'chapter', 'Before', 'Per Curiam|Curiam',
'causesubmitted', 'on briefs|briefs|brief', 'Division', 'absent', ' when',
' inof', 'Order', 'other', 'absent', 'tohis ', 'toother|TOOTHER|to other']

with open("judgeslistofregexes.txt", "wb") as fp:   #Pickling
    pickle.dump(judges_regexes, fp)

#with open("judgeslistofregexes.txt", "rb") as fp:   # Unpickling
#    list_regexes = pickle.load(fp)

#print list_regexes
